name: Cargo Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up MSYS2 for Windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64

      - name: Set up Rust for Windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: x86_64-pc-windows-gnu
      
      - name: Set up Rust
        if: ${{ startsWith(matrix.os, 'windows') != true }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cargo Check with --no-default-features
        run: cargo check --no-default-features

      - name: Cargo Check with --all-features
        run: cargo check --all-features
    
      - name: Cargo Clippy with --no-default-features
        run: cargo clippy --no-default-features -- -D warnings
    
      - name: Cargo Clippy with --all-features
        run: cargo clippy --all-features -- -D warnings

      - name: Cargo Test with --no-default-features
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: $env:RUST_BACKTRACE="full"; cargo test --no-default-features --target x86_64-pc-windows-gnu -- --nocapture

      - name: Cargo Test with --no-default-features
        # saves time on more expensive machines
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: RUST_BACKTRACE=full cargo test --no-default-features -- --nocapture
      
      - name: Cargo Test with --all-features
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: $env:RUST_BACKTRACE="full"; cargo test --all-features --target x86_64-pc-windows-gnu -- --nocapture
      
      - name: Cargo Test with --all-features
        if: ${{ startsWith(matrix.os, 'windows') != true }}
        run: RUST_BACKTRACE=full cargo test --all-features -- --nocapture
  